<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

      //Get Max X resaults of data
	 public function mydata($offset)
	{

    return $this->createQueryBuilder('u')
    ->setMaxResults($offset)
    ->getQuery()
    ->getResult()
;
	}
}



